### ISSUE TITLE
No CmakeList.txt in LinuxCmake

### ISSUE THREAD

**Issue by gortium** [NaoDevils/CodeRelease#2]
There is no CmakeList.txt in Make/LinuxCmake/. Cmakelist.txt is listed in .gitignore.

I would really like to get my hand on it to build the Bhuman code in Clion. I am not sure how to make it myself.

**Comment by thematrixincendies** [comment]
You are correct that there is no CMakeLists, in fact there are no project files for any IDE whatsoever in our sourcecode. We use a buildsystem called Mare, which I think is a self created buildchain from B Human. You can find Mare itself on github as well (look for craflin/mare). Anyways, we create project files dynamically using Mare. Inside Build/Common there are all the build instructions inside the different marefiles. In the respective IDE directories there are normally scripts calling Mare to create the project files.
CMake project files conversion is completely broken in Mare right now, because it is not very well maintained in Mare. I wrote a static CMakeLists some time ago which helps loading the code in CMake IDEs, but I can absolutely not recommend CLion right now, because code completion is totally broken when it comes to makros. You are better off using an IDE that supports autocompletion using clang. To simply compile using Linux it's best to just use the makefiles inside Build/LinuxMake. Just call "make all -jX" where X is the number of threads your CPU can handle inside this directory.

**Comment by gortium** [comment]
Thanks for the detailed answer !  :+1:  I will look Mare and for a clang IDE.

**Comment by gortium** [comment]
@Kamairo Do you know of any more documentation on Mare? i'm trying to include a new lib to the code. The lib come with its own cmakelist. Cant figure how to do it right now with mare. Thank you.
